//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACW_08346_464886_Client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ACW_08346_464886_ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HelloEcho", ReplyAction="http://tempuri.org/IService1/HelloEchoResponse")]
        string HelloEcho(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/HelloEcho", ReplyAction="http://tempuri.org/IService1/HelloEchoResponse")]
        System.Threading.Tasks.Task<string> HelloEchoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sort", ReplyAction="http://tempuri.org/IService1/SortResponse")]
        string[] Sort(string[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Sort", ReplyAction="http://tempuri.org/IService1/SortResponse")]
        System.Threading.Tasks.Task<string[]> SortAsync(string[] array);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PublicKey", ReplyAction="http://tempuri.org/IService1/PublicKeyResponse")]
        string[] PublicKey();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PublicKey", ReplyAction="http://tempuri.org/IService1/PublicKeyResponse")]
        System.Threading.Tasks.Task<string[]> PublicKeyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Decrypt", ReplyAction="http://tempuri.org/IService1/DecryptResponse")]
        void Decrypt(byte[] encryptedByteMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Decrypt", ReplyAction="http://tempuri.org/IService1/DecryptResponse")]
        System.Threading.Tasks.Task DecryptAsync(byte[] encryptedByteMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComputeSHA1", ReplyAction="http://tempuri.org/IService1/ComputeSHA1Response")]
        string ComputeSHA1(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComputeSHA1", ReplyAction="http://tempuri.org/IService1/ComputeSHA1Response")]
        System.Threading.Tasks.Task<string> ComputeSHA1Async(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComputeSHA256", ReplyAction="http://tempuri.org/IService1/ComputeSHA256Response")]
        string ComputeSHA256(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ComputeSHA256", ReplyAction="http://tempuri.org/IService1/ComputeSHA256Response")]
        System.Threading.Tasks.Task<string> ComputeSHA256Async(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ACW_08346_464886_Client.ServiceReference1.CompositeType GetDataUsingDataContract(ACW_08346_464886_Client.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ACW_08346_464886_Client.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ACW_08346_464886_Client.ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ACW_08346_464886_Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ACW_08346_464886_Client.ServiceReference1.IService1>, ACW_08346_464886_Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloEcho(int id) {
            return base.Channel.HelloEcho(id);
        }
        
        public System.Threading.Tasks.Task<string> HelloEchoAsync(int id) {
            return base.Channel.HelloEchoAsync(id);
        }
        
        public string[] Sort(string[] array) {
            return base.Channel.Sort(array);
        }
        
        public System.Threading.Tasks.Task<string[]> SortAsync(string[] array) {
            return base.Channel.SortAsync(array);
        }
        
        public string[] PublicKey() {
            return base.Channel.PublicKey();
        }
        
        public System.Threading.Tasks.Task<string[]> PublicKeyAsync() {
            return base.Channel.PublicKeyAsync();
        }
        
        public void Decrypt(byte[] encryptedByteMessage) {
            base.Channel.Decrypt(encryptedByteMessage);
        }
        
        public System.Threading.Tasks.Task DecryptAsync(byte[] encryptedByteMessage) {
            return base.Channel.DecryptAsync(encryptedByteMessage);
        }
        
        public string ComputeSHA1(string message) {
            return base.Channel.ComputeSHA1(message);
        }
        
        public System.Threading.Tasks.Task<string> ComputeSHA1Async(string message) {
            return base.Channel.ComputeSHA1Async(message);
        }
        
        public string ComputeSHA256(string message) {
            return base.Channel.ComputeSHA256(message);
        }
        
        public System.Threading.Tasks.Task<string> ComputeSHA256Async(string message) {
            return base.Channel.ComputeSHA256Async(message);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ACW_08346_464886_Client.ServiceReference1.CompositeType GetDataUsingDataContract(ACW_08346_464886_Client.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ACW_08346_464886_Client.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ACW_08346_464886_Client.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
